### ISSUE TITLE
Very high level of traffic usage

### ISSUE THREAD

**Issue by bruto8000** [moneyflow-dev/moneyflow#1]
https://github.com/moneyflow-dev/moneyflow/blob/23dcdd38abff9514925c199e2471fa8b959d7892/src/entities/transaction/model/incomes-store.ts#L30

Did I understand correctly that even when opening a page with 'income', the entire list will load?

**Comment by astsu-dev** [comment]
Hi, @bruto8000. You're correct. The application loads all transactions into memory (using Zustand store) upon startup. The application operates solely offline, with no HTTP requests; instead, it loads transactions from the Android Preferences API. Regarding memory usage, I've tested it with 100 000 transactions, and it only consumes 50MB of memory. What about rendering of large lists and performance? The application utilizes list virtualization to render lists, ensuring that only transactions within the viewport are rendered, even with a dataset as large as 100 000 transactions.
